### ISSUE TITLE
Strange values in the accelerations

### ISSUE THREAD

**Issue by evasola-alu** [hpparvi/ull_tp_2425#84]
Hi Hannu & all, 

I would like to ask about a certain issue that my code is having because I cannot seem to find the problem with it. 

My code compiles just fine, but the trajectories of the particles are off. I have tried with the stable 3-body configuration but also another one with just two particles on one axis so I can try and find the problem. When I try to run this second case, one of the particles suffers a constant acceleration, but the other one has a null acceleration for a few iterations, then gets an increasing acceleration for a few iterations, and then goes back to 0 for a bit. 

I suspect this problem is coming from the tree generation and assignment to cells, but I'm not sure where exactly. I have tried to locate the problem with no luck. 

Any ideas?

**Comment by urmagt** [comment]
I had a similar issue and fixed it by changing the 'belongs' function - it was assigning particles that were in the middle of two subcells to both subcells because angel de vicente's code uses all >= and <=. Changing half of them to < solved this issue.

**Comment by evasola-alu** [comment]
I tried this and indeed it completely fixed the issue. The 2-body test works exactly as expected and the 3-body problem is stable. Thank you so much!

**Comment by evasola-alu** [comment]
Issue fixed.
