### ISSUE TITLE
Help with tree

### ISSUE THREAD

**Issue by helena-rg** [hpparvi/ull_tp_2425#87]
My ex2 code doesn't work and I don't find the issue. :rotating_light:  It seems to be a problem with the tree algorithm (probably with Find Cell/Place Cell, because some particles are assigned to the same cell). I have compared with Eva's code but we don't find the difference that produces the problem :'(

**Comment by urmagt** [comment]
I don't know if it will completely fix the problem, but in your tree.f90 in the calcular_ranges, you have defined both calcular_ranges and valor_medio as integer arrays, which is going to cause issues. 
I hope this helps!

**Comment by helena-rg** [comment]
Now it works well, thank you so much!!
